{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "^C\n"
     ]
    }
   ],
   "source": [
    "!pip uninstall pandas\n",
    "!pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.util failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.compat failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas._typing failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas._config failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.config_init failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\config_init.py\", line 17, in <module>\n",
      "    import pandas._config.config as cf\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas._libs.tslibs failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_libs\\tslibs\\__init__.py\", line 39, in <module>\n",
      "    from pandas._libs.tslibs import dtypes  # pylint: disable=import-self\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "ImportError: cannot import name 'iNaT' from 'pandas._libs.tslibs' (c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_libs\\tslibs\\__init__.py)\n",
      "]\n",
      "[autoreload of pandas._libs failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.errors failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.missing failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\missing.py\", line 19, in <module>\n",
      "    import pandas._libs.missing as libmissing\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.io failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.io._util failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\_util.py\", line 7, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.construction failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\construction.py\", line 64, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.computation.expressions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\computation\\expressions.py\", line 195, in <module>\n",
      "    set_use_numexpr(get_option(\"compute.use_numexpr\"))\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 274, in __call__\n",
      "    return self.__func__(*args, **kwds)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 146, in _get_option\n",
      "    key = _get_single_key(pat, silent)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 132, in _get_single_key\n",
      "    raise OptionError(f\"No such keys(s): {repr(pat)}\")\n",
      "pandas._config.config.OptionError: No such keys(s): 'compute.use_numexpr'\n",
      "]\n",
      "[autoreload of pandas.core.ops.array_ops failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\base.py\", line 30, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.nanops failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\nanops.py\", line 64, in <module>\n",
      "    set_use_bottleneck(get_option(\"compute.use_bottleneck\"))\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 274, in __call__\n",
      "    return self.__func__(*args, **kwds)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 146, in _get_option\n",
      "    key = _get_single_key(pat, silent)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\_config\\config.py\", line 132, in _get_single_key\n",
      "    raise OptionError(f\"No such keys(s): {repr(pat)}\")\n",
      "pandas._config.config.OptionError: No such keys(s): 'compute.use_bottleneck'\n",
      "]\n",
      "[autoreload of pandas.core.arrays.masked failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\masked.py\", line 74, in <module>\n",
      "    from pandas.core.array_algos import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.floating failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\floating.py\", line 156, in <module>\n",
      "    @register_extension_dtype\n",
      "     ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\base.py\", line 497, in register_extension_dtype\n",
      "    _registry.register(cls)\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\base.py\", line 527, in register\n",
      "    raise ValueError(\"can only register pandas extension dtypes\")\n",
      "ValueError: can only register pandas extension dtypes\n",
      "]\n",
      "[autoreload of pandas.core.arrays.integer failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\integer.py\", line 207, in <module>\n",
      "    @register_extension_dtype\n",
      "     ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\base.py\", line 497, in register_extension_dtype\n",
      "    _registry.register(cls)\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\base.py\", line 527, in register\n",
      "    raise ValueError(\"can only register pandas extension dtypes\")\n",
      "ValueError: can only register pandas extension dtypes\n",
      "]\n",
      "[autoreload of pandas.core.strings.object_array failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\strings\\object_array.py\", line 17, in <module>\n",
      "    import pandas._libs.missing as libmissing\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.numpy_ failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\numpy_.py\", line 12, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.string_ failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\string_.py\", line 20, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.tseries failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.arrays.arrow.array failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 66, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.boolean failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\boolean.py\", line 22, in <module>\n",
      "    from pandas.core.array_algos import masked_accumulations\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "ImportError: cannot import name BooleanDtype\n",
      "]\n",
      "[autoreload of pandas.core.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\base.py\", line 34, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.categorical failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\categorical.py\", line 25, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimelike.py\", line 72, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimes.py\", line 64, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\timedeltas.py\", line 39, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.interval failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\interval.py\", line 42, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.period failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\period.py\", line 77, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.sparse.array failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\sparse\\array.py\", line 22, in <module>\n",
      "    import pandas._libs.sparse as splib\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.apply failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\apply.py\", line 57, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 37, in <module>\n",
      "    import pandas._libs.join as libjoin\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.range failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\range.py\", line 27, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\datetimelike.py\", line 36, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\datetimes.py\", line 42, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.multi failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\multi.py\", line 45, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\timedeltas.py\", line 26, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.interval failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\interval.py\", line 67, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.period failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\period.py\", line 38, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.indexing failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexing.py\", line 68, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.internals.blocks failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 94, in <module>\n",
      "    import pandas.core.algorithms as algos\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.internals.managers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 55, in <module>\n",
      "    import pandas.core.algorithms as algos\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.internals.array_manager failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\array_manager.py\", line 49, in <module>\n",
      "    import pandas.core.algorithms as algos\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.concat failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 38, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "ImportError: cannot import name 'concat' from 'pandas.core.reshape.concat' (c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\concat.py)\n",
      "]\n",
      "[autoreload of pandas.io.formats.format failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\formats\\format.py\", line 71, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.window.rolling failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\window\\rolling.py\", line 26, in <module>\n",
      "    import pandas._libs.window.aggregations as window_aggregations\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.window.ewm failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\window\\ewm.py\", line 11, in <module>\n",
      "    import pandas._libs.window.aggregations as window_aggregations\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.generic failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\generic.py\", line 95, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.melt failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\melt.py\", line 14, in <module>\n",
      "    import pandas.core.algorithms as algos\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.arrays failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.io.formats.info failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\formats\\info.py\", line 13, in <module>\n",
      "    from pandas.io.formats import format as fmt\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.plotting failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.series failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py\", line 44, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.frame failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 59, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.grouper failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\groupby\\grouper.py\", line 37, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.ops failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\groupby\\ops.py\", line 25, in <module>\n",
      "    import pandas._libs.groupby as libgroupby\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.groupby failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 44, in <module>\n",
      "    import pandas._libs.groupby as libgroupby\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.generic failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\groupby\\generic.py\", line 67, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.computation.align failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\computation\\align.py\", line 27, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.computation.ops failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 25, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.computation.engines failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\computation\\engines.py\", line 20, in <module>\n",
      "    from pandas.io.formats import printing\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.computation.expr failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 23, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.merge failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\merge.py\", line 78, in <module>\n",
      "    from pandas import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.pivot failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\pivot.py\", line 36, in <module>\n",
      "    import pandas.core.common as com\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.tile failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\reshape\\tile.py\", line 37, in <module>\n",
      "    from pandas import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.api.extensions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.api' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.api.indexers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.api' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.interchange.utils failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\interchange\\utils.py\", line 19, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.core.interchange.from_dataframe failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\interchange\\from_dataframe.py\", line 12, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 31, in <module>\n",
      "    from pandas.io.json._json import JsonReader\n",
      "AttributeError: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)\n",
      "]\n",
      "[autoreload of pandas.api.interchange failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.api' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.api.types failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.api' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.core.resample failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 131, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 866, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\resample.py\", line 29, in <module>\n",
      "    from pandas.compat.numpy import function as nv\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py\", line 151, in <module>\n",
      "    from pandas import api, arrays, errors, io, plotting, tseries\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py\", line 2, in <module>\n",
      "    from pandas.api import (\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py\", line 12, in <module>\n",
      "    from pandas.core.resample import (\n",
      "ImportError: cannot import name 'DatetimeIndexResamplerGroupby' from 'pandas.core.resample' (c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\resample.py)\n",
      "]\n",
      "[autoreload of pandas.io.json._normalize failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.io.json' not in sys.modules\n",
      "]\n",
      "[autoreload of pandas.io.json._table_schema failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Candela\\AppData\\Roaming\\Python\\Python312\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\__init__.py\", line 121, in reload\n",
      "    raise ImportError(f\"parent {parent_name!r} not in sys.modules\",\n",
      "ImportError: parent 'pandas.io.json' not in sys.modules\n",
      "]\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[10], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpathlib\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Path\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdetection_helper\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m create_DF\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py:151\u001b[0m\n\u001b[0;32m    132\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcore\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcomputation\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapi\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;28meval\u001b[39m\n\u001b[0;32m    134\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcore\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mreshape\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapi\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m    135\u001b[0m     concat,\n\u001b[0;32m    136\u001b[0m     lreshape,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    148\u001b[0m     qcut,\n\u001b[0;32m    149\u001b[0m )\n\u001b[1;32m--> 151\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m api, arrays, errors, io, plotting, tseries\n\u001b[0;32m    152\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m testing\n\u001b[0;32m    153\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutil\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_print_versions\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m show_versions\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\__init__.py:2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;124;03m\"\"\" public toolkit API \"\"\"\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapi\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m      3\u001b[0m     extensions,\n\u001b[0;32m      4\u001b[0m     indexers,\n\u001b[0;32m      5\u001b[0m     interchange,\n\u001b[0;32m      6\u001b[0m     types,\n\u001b[0;32m      7\u001b[0m     typing,\n\u001b[0;32m      8\u001b[0m )\n\u001b[0;32m     10\u001b[0m __all__ \u001b[38;5;241m=\u001b[39m [\n\u001b[0;32m     11\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minterchange\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     12\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mextensions\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     15\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtyping\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     16\u001b[0m ]\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\api\\typing\\__init__.py:31\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcore\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mwindow\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     20\u001b[0m     Expanding,\n\u001b[0;32m     21\u001b[0m     ExpandingGroupby,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     26\u001b[0m     Window,\n\u001b[0;32m     27\u001b[0m )\n\u001b[0;32m     29\u001b[0m \u001b[38;5;66;03m# TODO: Can't import Styler without importing jinja2\u001b[39;00m\n\u001b[0;32m     30\u001b[0m \u001b[38;5;66;03m# from pandas.io.formats.style import Styler\u001b[39;00m\n\u001b[1;32m---> 31\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mjson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_json\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m JsonReader\n\u001b[0;32m     32\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mstata\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m StataReader\n\u001b[0;32m     34\u001b[0m __all__ \u001b[38;5;241m=\u001b[39m [\n\u001b[0;32m     35\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDataFrameGroupBy\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     36\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDatetimeIndexResamplerGroupby\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     54\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mWindow\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     55\u001b[0m ]\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\json\\__init__.py:1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mjson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_json\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m      2\u001b[0m     read_json,\n\u001b[0;32m      3\u001b[0m     to_json,\n\u001b[0;32m      4\u001b[0m     ujson_dumps,\n\u001b[0;32m      5\u001b[0m     ujson_loads,\n\u001b[0;32m      6\u001b[0m )\n\u001b[0;32m      7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mjson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_table_schema\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m build_table_schema\n\u001b[0;32m      9\u001b[0m __all__ \u001b[38;5;241m=\u001b[39m [\n\u001b[0;32m     10\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mujson_dumps\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     11\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mujson_loads\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     14\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbuild_table_schema\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     15\u001b[0m ]\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\json\\_json.py:71\u001b[0m\n\u001b[0;32m     66\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mjson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_normalize\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m convert_to_line_delimits\n\u001b[0;32m     67\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mjson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_table_schema\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     68\u001b[0m     build_table_schema,\n\u001b[0;32m     69\u001b[0m     parse_table_schema,\n\u001b[0;32m     70\u001b[0m )\n\u001b[1;32m---> 71\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mparsers\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mreaders\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m validate_integer\n\u001b[0;32m     73\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m TYPE_CHECKING:\n\u001b[0;32m     74\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mcollections\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mabc\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     75\u001b[0m         Hashable,\n\u001b[0;32m     76\u001b[0m         Mapping,\n\u001b[0;32m     77\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\__init__.py:1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mio\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mparsers\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mreaders\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m      2\u001b[0m     TextFileReader,\n\u001b[0;32m      3\u001b[0m     TextParser,\n\u001b[0;32m      4\u001b[0m     read_csv,\n\u001b[0;32m      5\u001b[0m     read_fwf,\n\u001b[0;32m      6\u001b[0m     read_table,\n\u001b[0;32m      7\u001b[0m )\n\u001b[0;32m      9\u001b[0m __all__ \u001b[38;5;241m=\u001b[39m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTextFileReader\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTextParser\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mread_csv\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mread_fwf\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mread_table\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[1;32mc:\\Users\\Candela\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:32\u001b[0m\n\u001b[0;32m     29\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_config\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m using_copy_on_write\n\u001b[0;32m     31\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_libs\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m lib\n\u001b[1;32m---> 32\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_libs\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mparsers\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m STR_NA_VALUES\n\u001b[0;32m     33\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     34\u001b[0m     AbstractMethodError,\n\u001b[0;32m     35\u001b[0m     ParserWarning,\n\u001b[0;32m     36\u001b[0m )\n\u001b[0;32m     37\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutil\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_decorators\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Appender\n",
      "File \u001b[1;32mparsers.pyx:1418\u001b[0m, in \u001b[0;36minit pandas._libs.parsers\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: partially initialized module 'pandas' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)"
     ]
    }
   ],
   "source": [
    "\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from detection_helper import create_DF\n",
    "from matplotlib import pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Path' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m train_files \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlist\u001b[39m(\u001b[43mPath\u001b[49m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mdataset/annotations/\u001b[39m\u001b[38;5;124m\"\u001b[39m)\u001b[38;5;241m.\u001b[39mglob(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m**/*xml\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m      2\u001b[0m \u001b[38;5;66;03m# val_files = list(Path(\"dataset/annotations/\").glob(\"**/*xml\"))\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28mprint\u001b[39m(train_files)\n",
      "\u001b[1;31mNameError\u001b[0m: name 'Path' is not defined"
     ]
    }
   ],
   "source": [
    "train_files = list(Path(\"dataset/annotations/\").glob(\"**/*xml\"))\n",
    "# val_files = list(Path(\"dataset/annotations/\").glob(\"**/*xml\"))\n",
    "\n",
    "print(train_files)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = create_DF(train_files,Path(\"dataset/images/\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# df_val = create_DF(val_files,Path(\"Dataset/validation/Apple_Grape_Cantaloupe_Watermelon_Pomegranate_Pineapple_Peach_Mango_Banana_Lemon_Tomato_Strawberry_Pear/\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>label</th>\n",
       "      <th>left</th>\n",
       "      <th>top</th>\n",
       "      <th>right</th>\n",
       "      <th>bottom</th>\n",
       "      <th>height</th>\n",
       "      <th>width</th>\n",
       "      <th>image</th>\n",
       "      <th>image_name</th>\n",
       "      <th>center_x</th>\n",
       "      <th>center_y</th>\n",
       "      <th>delta_x</th>\n",
       "      <th>delta_y</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Apple</td>\n",
       "      <td>236.16</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>625.92</td>\n",
       "      <td>342.140654</td>\n",
       "      <td>1024</td>\n",
       "      <td>683</td>\n",
       "      <td>Dataset/train/Apple_Grape_Cantaloupe_Watermelo...</td>\n",
       "      <td>837bf3be7055dc46</td>\n",
       "      <td>431.04</td>\n",
       "      <td>171.070327</td>\n",
       "      <td>389.76</td>\n",
       "      <td>342.140654</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Apple</td>\n",
       "      <td>318.72</td>\n",
       "      <td>44.209224</td>\n",
       "      <td>466.56</td>\n",
       "      <td>246.674329</td>\n",
       "      <td>1024</td>\n",
       "      <td>683</td>\n",
       "      <td>Dataset/train/Apple_Grape_Cantaloupe_Watermelo...</td>\n",
       "      <td>837bf3be7055dc46</td>\n",
       "      <td>392.64</td>\n",
       "      <td>145.441777</td>\n",
       "      <td>147.84</td>\n",
       "      <td>202.465105</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Grape</td>\n",
       "      <td>285.44</td>\n",
       "      <td>390.194485</td>\n",
       "      <td>469.12</td>\n",
       "      <td>565.749390</td>\n",
       "      <td>1024</td>\n",
       "      <td>683</td>\n",
       "      <td>Dataset/train/Apple_Grape_Cantaloupe_Watermelo...</td>\n",
       "      <td>116b98c8f1a2538c</td>\n",
       "      <td>377.28</td>\n",
       "      <td>477.971938</td>\n",
       "      <td>183.68</td>\n",
       "      <td>175.554905</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Strawberry</td>\n",
       "      <td>321.28</td>\n",
       "      <td>484.231821</td>\n",
       "      <td>493.44</td>\n",
       "      <td>654.609170</td>\n",
       "      <td>1024</td>\n",
       "      <td>841</td>\n",
       "      <td>Dataset/train/Apple_Grape_Cantaloupe_Watermelo...</td>\n",
       "      <td>b1e2809b606fb594</td>\n",
       "      <td>407.36</td>\n",
       "      <td>569.420496</td>\n",
       "      <td>172.16</td>\n",
       "      <td>170.377349</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Strawberry</td>\n",
       "      <td>111.36</td>\n",
       "      <td>332.428798</td>\n",
       "      <td>187.52</td>\n",
       "      <td>450.924857</td>\n",
       "      <td>1024</td>\n",
       "      <td>841</td>\n",
       "      <td>Dataset/train/Apple_Grape_Cantaloupe_Watermelo...</td>\n",
       "      <td>b1e2809b606fb594</td>\n",
       "      <td>149.44</td>\n",
       "      <td>391.676828</td>\n",
       "      <td>76.16</td>\n",
       "      <td>118.496059</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        label    left         top   right      bottom  height  width  \\\n",
       "0       Apple  236.16    0.000000  625.92  342.140654    1024    683   \n",
       "1       Apple  318.72   44.209224  466.56  246.674329    1024    683   \n",
       "2       Grape  285.44  390.194485  469.12  565.749390    1024    683   \n",
       "3  Strawberry  321.28  484.231821  493.44  654.609170    1024    841   \n",
       "4  Strawberry  111.36  332.428798  187.52  450.924857    1024    841   \n",
       "\n",
       "                                               image        image_name  \\\n",
       "0  Dataset/train/Apple_Grape_Cantaloupe_Watermelo...  837bf3be7055dc46   \n",
       "1  Dataset/train/Apple_Grape_Cantaloupe_Watermelo...  837bf3be7055dc46   \n",
       "2  Dataset/train/Apple_Grape_Cantaloupe_Watermelo...  116b98c8f1a2538c   \n",
       "3  Dataset/train/Apple_Grape_Cantaloupe_Watermelo...  b1e2809b606fb594   \n",
       "4  Dataset/train/Apple_Grape_Cantaloupe_Watermelo...  b1e2809b606fb594   \n",
       "\n",
       "   center_x    center_y  delta_x     delta_y  \n",
       "0    431.04  171.070327   389.76  342.140654  \n",
       "1    392.64  145.441777   147.84  202.465105  \n",
       "2    377.28  477.971938   183.68  175.554905  \n",
       "3    407.36  569.420496   172.16  170.377349  \n",
       "4    149.44  391.676828    76.16  118.496059  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>label</th>\n",
       "      <th>left</th>\n",
       "      <th>top</th>\n",
       "      <th>right</th>\n",
       "      <th>bottom</th>\n",
       "      <th>height</th>\n",
       "      <th>width</th>\n",
       "      <th>image</th>\n",
       "      <th>image_name</th>\n",
       "      <th>center_x</th>\n",
       "      <th>center_y</th>\n",
       "      <th>delta_x</th>\n",
       "      <th>delta_y</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Tomato</td>\n",
       "      <td>72.387584</td>\n",
       "      <td>119.736162</td>\n",
       "      <td>793.486336</td>\n",
       "      <td>619.030503</td>\n",
       "      <td>1024</td>\n",
       "      <td>819</td>\n",
       "      <td>Dataset/validation/Apple_Grape_Cantaloupe_Wate...</td>\n",
       "      <td>604835415b761f30</td>\n",
       "      <td>432.936960</td>\n",
       "      <td>369.383333</td>\n",
       "      <td>721.098752</td>\n",
       "      <td>499.294341</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Lemon</td>\n",
       "      <td>89.567232</td>\n",
       "      <td>152.054784</td>\n",
       "      <td>441.594880</td>\n",
       "      <td>461.195520</td>\n",
       "      <td>1024</td>\n",
       "      <td>768</td>\n",
       "      <td>Dataset/validation/Apple_Grape_Cantaloupe_Wate...</td>\n",
       "      <td>b39532c4a3bd5d83</td>\n",
       "      <td>265.581056</td>\n",
       "      <td>306.625152</td>\n",
       "      <td>352.027648</td>\n",
       "      <td>309.140736</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Strawberry</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.053248</td>\n",
       "      <td>1023.358976</td>\n",
       "      <td>1024.000000</td>\n",
       "      <td>1024</td>\n",
       "      <td>1024</td>\n",
       "      <td>Dataset/validation/Apple_Grape_Cantaloupe_Wate...</td>\n",
       "      <td>e0be14f0681f4b39</td>\n",
       "      <td>511.679488</td>\n",
       "      <td>512.026624</td>\n",
       "      <td>1023.358976</td>\n",
       "      <td>1023.946752</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Lemon</td>\n",
       "      <td>236.441600</td>\n",
       "      <td>90.215200</td>\n",
       "      <td>905.010176</td>\n",
       "      <td>573.973625</td>\n",
       "      <td>1024</td>\n",
       "      <td>575</td>\n",
       "      <td>Dataset/validation/Apple_Grape_Cantaloupe_Wate...</td>\n",
       "      <td>730020d358ea3d82</td>\n",
       "      <td>570.725888</td>\n",
       "      <td>332.094412</td>\n",
       "      <td>668.568576</td>\n",
       "      <td>483.758425</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Lemon</td>\n",
       "      <td>320.348160</td>\n",
       "      <td>30.697525</td>\n",
       "      <td>724.350976</td>\n",
       "      <td>119.152075</td>\n",
       "      <td>1024</td>\n",
       "      <td>575</td>\n",
       "      <td>Dataset/validation/Apple_Grape_Cantaloupe_Wate...</td>\n",
       "      <td>730020d358ea3d82</td>\n",
       "      <td>522.349568</td>\n",
       "      <td>74.924800</td>\n",
       "      <td>404.002816</td>\n",
       "      <td>88.454550</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        label        left         top        right       bottom  height  \\\n",
       "0      Tomato   72.387584  119.736162   793.486336   619.030503    1024   \n",
       "1       Lemon   89.567232  152.054784   441.594880   461.195520    1024   \n",
       "2  Strawberry    0.000000    0.053248  1023.358976  1024.000000    1024   \n",
       "3       Lemon  236.441600   90.215200   905.010176   573.973625    1024   \n",
       "4       Lemon  320.348160   30.697525   724.350976   119.152075    1024   \n",
       "\n",
       "   width                                              image        image_name  \\\n",
       "0    819  Dataset/validation/Apple_Grape_Cantaloupe_Wate...  604835415b761f30   \n",
       "1    768  Dataset/validation/Apple_Grape_Cantaloupe_Wate...  b39532c4a3bd5d83   \n",
       "2   1024  Dataset/validation/Apple_Grape_Cantaloupe_Wate...  e0be14f0681f4b39   \n",
       "3    575  Dataset/validation/Apple_Grape_Cantaloupe_Wate...  730020d358ea3d82   \n",
       "4    575  Dataset/validation/Apple_Grape_Cantaloupe_Wate...  730020d358ea3d82   \n",
       "\n",
       "     center_x    center_y      delta_x      delta_y  \n",
       "0  432.936960  369.383333   721.098752   499.294341  \n",
       "1  265.581056  306.625152   352.027648   309.140736  \n",
       "2  511.679488  512.026624  1023.358976  1023.946752  \n",
       "3  570.725888  332.094412   668.568576   483.758425  \n",
       "4  522.349568   74.924800   404.002816    88.454550  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_val.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['Apple', 'Grape', 'Strawberry', 'Banana', 'Lemon', 'Pomegranate',\n",
       "       'Mango', 'Peach', 'Tomato', 'Pear', 'Watermelon', 'Pineapple',\n",
       "       'Cantaloupe'], dtype=object)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "classes = df_train[\"label\"].unique()\n",
    "classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "classes_idx = {clase:idx for idx,clase in enumerate(classes)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "13"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cant_classes = len(classes)\n",
    "cant_classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "with open(\"data.pkl\",\"wb\") as f:\n",
    "    pickle.dump((df_train, df_val, train_files, val_files, classes_idx, cant_classes, classes),f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
